version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=lmaye
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
      - ./logs:/data/logs
    ports:
      - 27017:27017
