version: "3"
services:
  hexo-admin:
    build: ./hexo-blog-admin
    container_name: hexo-blog-admin
    restart: on-failure
    command: uwsgi --ini /webapp/hexo-blog-admin.ini
    working_dir: /webapp
    ports:
      - 5000:5000
    volumes:
      - ./hexo-blog-admin:/webapp
#      - ./logs:/logs

  nginx:
    container_name: blog-nginx
    image: nginx:1.16
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx

  minio:
    # 容器名称
    container_name: blog-minio
    # 镜像:版本
    image: minio/minio:latest
    # 重启机制
    # -- no: 禁止自动重启容器(默认);
    # -- always: 无论如何容器都会重启;
    # -- on-failure: 当出现on-failure报错时, 容器重新启动;
    restart: on-failure
    command: server /data
    # 端口
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: YouGuess
    # 持久化挂载
    volumes:
      # Nginx代理访问资源
      - ./nginx/www/files:/data
      - ./minio/conf:/root/.minio

  mongodb:
    container_name: blog-mongo
    image: mongo:4.4.3
    restart: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=YouGuess
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/logs:/data/logs
    ports:
      - 27017:27017